from __future__ import annotations

from typing import List, Optional, Sequence, Tuple, Literal

import numpy as np
import numpy.typing as npt

Bin = Tuple[Tuple[float, float], int]
FloatArray = npt.NDArray[np.float64]
BoolArray = npt.NDArray[np.bool_]
ValueInput = Sequence[float] | FloatArray
OutOfRangeMode = Literal["Clip", "Ignore", "Error"]


class SparseHistogram:
    def __init__(self, bin_width: float) -> None: ...

    def update(self, values: ValueInput) -> None: ...

    def update_np(self, values: FloatArray) -> None: ...

    def update_np_mask(self, values: FloatArray, mask: BoolArray) -> None: ...

    def get(self) -> List[Bin]: ...


class DenseHistogram:
    def __init__(
        self,
        range: Tuple[float, float],
        num_bins: int,
        out_of_range: OutOfRangeMode,
    ) -> None: ...

    def update(self, values: ValueInput) -> None: ...

    def update_np(self, values: FloatArray) -> None: ...

    def update_np_mask(self, values: FloatArray, mask: BoolArray) -> None: ...

    def get(self) -> List[Bin]: ...


class HistogramSnapshot:
    @property
    def index(self) -> int: ...

    @property
    def label(self) -> Optional[str]: ...

    def bins(self) -> List[Bin]: ...

    def total(self) -> int: ...


class SnapshotDiff:
    @property
    def start_index(self) -> int: ...

    @property
    def end_index(self) -> int: ...

    @property
    def start_label(self) -> Optional[str]: ...

    @property
    def end_label(self) -> Optional[str]: ...

    def bins(self) -> List[Bin]: ...

    def total(self) -> int: ...


class HistogramRecorder:
    @staticmethod
    def from_sparse(bin_width: float, max_snapshots: Optional[int] = ...) -> "HistogramRecorder": ...

    @staticmethod
    def from_dense(
        range: Tuple[float, float],
        num_bins: int,
        out_of_range: OutOfRangeMode,
        max_snapshots: Optional[int] = ...,
    ) -> "HistogramRecorder": ...

    def update(self, values: ValueInput) -> None: ...

    def update_np(self, values: FloatArray) -> None: ...

    def update_np_mask(self, values: FloatArray, mask: BoolArray) -> None: ...

    def get(self) -> List[Bin]: ...

    def snapshot(self, label: Optional[str] = ...) -> HistogramSnapshot: ...

    def latest(self) -> Optional[HistogramSnapshot]: ...

    def get_snapshot(self, index: int) -> HistogramSnapshot: ...

    def diff(self, later_index: int, earlier_index: int) -> SnapshotDiff: ...

    def drain_snapshots(self, end_index: int) -> int: ...

    def clear_snapshots(self) -> None: ...

    def __len__(self) -> int: ...
